version: "3.8"

services:
  express-project:
    container_name: express-project
    image: express-project
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app

networks:
  default:
    external:
      name: default-network
